version: '2'
services:
    dndbot:
        container_name: dndbot
        image: dndbot
        build: .
        volumes:
            - ./:/opt/dndbot
        command: bash -c 'cd /opt/dndbot/src && python3 -u bot.py'
        restart: always
        network_mode: bridge
